// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Todo list
From the todo list tutorial on goswagger.io


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 1.0.0

    Consumes:
    - application/io.goswagger.examples.todo-list.v1+json

    Produces:
    - application/io.goswagger.examples.todo-list.v1+json

swagger:meta
*/
package restapi
